version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: pg_json_test
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"

  mongo:
    image: mongo:6
    container_name: mongo_json_test
    restart: always
    ports:
      - "27017:27017"